"use client";

import { useState, useEffect, useRef } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import {
  FileText,
  Building2,
  AlignLeft,
  AlignCenter,
  AlignRight,
  Upload,
  Save,
  Check,
  X,
  Palette,
  Image as ImageIcon,
  Type,
  Minus,
  FileSignature,
  RotateCcw,
  Trash2,
  Clock,
  Bookmark,
} from "lucide-react";

import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { saveReportTemplateDesign, getReportTemplateDesign, saveReportPreset, getReportPresets, deleteReportPreset } from "@/app/settings/bill-design-actions";
import { ReportPreview } from "@/components/reports/report-preview";

// Report Design Schema - Header and Footer only
const reportDesignSchema = z.object({
  // Header Configuration
  headerConfig: z.object({
    // Show/Hide Header
    showHeader: z.boolean().default(true),
    // Logo Settings
    showLogo: z.boolean().default(true),
    logo: z.string().nullable().optional(),
    logoPosition: z.enum(["left", "center", "right"]).default("left"),
    logoSize: z.enum(["small", "medium", "large"]).default("medium"),
    
    // Business Information
    showBusinessName: z.boolean().default(true),
    showAddress: z.boolean().default(true),
    showContactInfo: z.boolean().default(true),
    showTaxInfo: z.boolean().default(false),
    businessName: z.string().default("LPG Nexus Distribution"),
    address: z.string().default("123 Business Street, City, State 12345"),
    phoneNumber: z.string().default("+91 9876543210"),
    email: z.string().default("info@lpgnexus.com"),
    ntnGst: z.string().optional(),
    
    // Header Text Styling
    fontSize: z.number().min(8).max(24).default(14),
    fontWeight: z.enum(["regular", "medium", "bold"]).default("regular"),
    textColor: z.string().regex(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/, "Invalid color format").default("#000000"),
    lineHeight: z.number().min(1).max(2).default(1.5),
    
    // Alignment & Layout
    textAlignment: z.enum(["left", "center", "right"]).default("left"),
    headerLayout: z.enum(["horizontal", "vertical"]).default("horizontal"),
    
    // Header Divider
    showDivider: z.boolean().default(true),
    dividerStyle: z.enum(["solid", "dotted", "dashed"]).default("solid"),
    dividerColor: z.string().regex(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/, "Invalid color format").default("#e2e8f0"),
    dividerThickness: z.number().min(1).max(5).default(1),
    // Header Margins
    topMargin: z.number().min(0).max(100).default(0),
    bottomMargin: z.number().min(-50).max(100).default(20),
  }),
  
  // Footer Configuration
  footerConfig: z.object({
    // Show/Hide Footer
    showFooter: z.boolean().default(true),
    // Footer Content
    footerLeftText: z.string().default("Generated by LPG Nexus"),
    footerCenterText: z.string().optional(),
    footerRightText: z.string().optional(),
    showPageNumber: z.boolean().default(true),
    showPrintedDate: z.boolean().default(true),
    showSignatureLine: z.boolean().default(false),
    
    // Footer Styling
    fontSize: z.number().min(8).max(24).default(12),
    textColor: z.string().regex(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/, "Invalid color format").default("#666666"),
    alignment: z.enum(["left", "center", "right"]).default("center"),
    
    // Signature (Optional)
    signatureLabel: z.string().default("Authorized Signature"),
    showSignature: z.boolean().default(false),
    signatureAlignment: z.enum(["left", "center", "right"]).default("center"),
    signatureLineSpacing: z.number().min(0).max(30).default(8),
    // Footer Margins
    topMargin: z.number().min(-50).max(100).default(20),
    bottomMargin: z.number().min(0).max(100).default(0),
  }),
});

type ReportDesignFormValues = z.infer<typeof reportDesignSchema>;

const logoSizeMap = {
  small: 80,
  medium: 120,
  large: 160,
};

export function ReportDesigningTab() {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [toast, setToast] = useState<{ message: string; type: "success" | "error" } | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [logoFile, setLogoFile] = useState<File | null>(null);
  const [logoPreview, setLogoPreview] = useState<string | null>(null);
  const logoInputRef = useRef<HTMLInputElement>(null);
  const [presets, setPresets] = useState<{ saved: any[]; history: any[] }>({ saved: [], history: [] });
  const [presetName, setPresetName] = useState("");
  const [isSavingPreset, setIsSavingPreset] = useState(false);

  const form = useForm<ReportDesignFormValues>({
    resolver: zodResolver(reportDesignSchema),
    defaultValues: {
      headerConfig: {
        showHeader: true,
        showLogo: true,
        logo: null,
        logoPosition: "left",
        logoSize: "medium",
        showBusinessName: true,
        showAddress: true,
        showContactInfo: true,
        showTaxInfo: false,
        businessName: "LPG Nexus Distribution",
        address: "123 Business Street, City, State 12345",
        phoneNumber: "+91 9876543210",
        email: "info@lpgnexus.com",
        ntnGst: "",
        fontSize: 14,
        fontWeight: "regular",
        textColor: "#000000",
        lineHeight: 1.5,
        textAlignment: "left",
        headerLayout: "horizontal",
        showDivider: true,
        dividerStyle: "solid",
        dividerColor: "#e2e8f0",
        dividerThickness: 1,
        topMargin: 0,
        bottomMargin: 20,
      },
      footerConfig: {
        showFooter: true,
        footerLeftText: "Generated by LPG Nexus",
        footerCenterText: "",
        footerRightText: "",
        showPageNumber: true,
        showPrintedDate: true,
        showSignatureLine: false,
        fontSize: 12,
        textColor: "#666666",
        alignment: "center",
        signatureLabel: "Authorized Signature",
        showSignature: false,
        signatureAlignment: "center",
        signatureLineSpacing: 8,
        topMargin: 20,
        bottomMargin: 0,
      },
    },
  });

  // Load saved design and presets on mount
  useEffect(() => {
    async function loadSavedDesign() {
      try {
        const [designResult, presetsResult] = await Promise.all([
          getReportTemplateDesign(),
          getReportPresets(),
        ]);

        if (designResult.success && designResult.data) {
          const saved = designResult.data as ReportDesignFormValues;
          form.reset(saved);
          
          // Load logo preview if exists
          if (saved.headerConfig?.logo) {
            setLogoPreview(saved.headerConfig.logo);
          }
        }

        if (presetsResult.success && presetsResult.data) {
          setPresets(presetsResult.data);
        } else if (!presetsResult.success) {
          console.warn("Failed to load presets:", presetsResult.error);
          // Set empty presets to prevent UI errors
          setPresets({ saved: [], history: [] });
        }
      } catch (error) {
        console.error("Error loading report template design:", error);
        // Set empty presets on error to prevent UI breakage
        setPresets({ saved: [], history: [] });
      } finally {
        setIsLoading(false);
      }
    }
    loadSavedDesign();
  }, [form]);

  // Handle logo upload
  function handleLogoUpload(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (file && (file.type === "image/png" || file.type === "image/jpeg" || file.type === "image/jpg")) {
      setLogoFile(file);
      const reader = new FileReader();
      reader.onloadend = () => {
        const base64String = reader.result as string;
        setLogoPreview(base64String);
        form.setValue("headerConfig.logo", base64String);
      };
      reader.readAsDataURL(file);
    }
  }

  async function onSubmit(data: ReportDesignFormValues) {
    setIsSubmitting(true);
    try {
      const result = await saveReportTemplateDesign(data);
      
      if (result.success) {
        setToast({ 
          message: result.message || "Report design saved successfully!", 
          type: "success" 
        });
      } else {
        setToast({
          message: result.error || "Failed to save report design",
          type: "error",
        });
      }
      
      setTimeout(() => {
        setToast(null);
      }, 5000);
    } catch (error) {
      setToast({
        message: error instanceof Error ? error.message : "Failed to save report design",
        type: "error",
      });
    } finally {
      setIsSubmitting(false);
    }
  }

  async function handleSavePreset() {
    if (!presetName.trim()) {
      setToast({
        message: "Please enter a preset name",
        type: "error",
      });
      setTimeout(() => setToast(null), 3000);
      return;
    }
    
    setIsSavingPreset(true);
    try {
      const currentValues = form.getValues();
      const result = await saveReportPreset(presetName.trim(), currentValues);
      
      if (result.success) {
        setToast({
          message: result.message || "Preset saved successfully!",
          type: "success",
        });
        setPresetName("");
        
        // Reload presets
        const presetsResult = await getReportPresets();
        if (presetsResult.success && presetsResult.data) {
          setPresets(presetsResult.data);
        } else if (!presetsResult.success && presetsResult.error) {
          // If error but we saved successfully, show warning
          console.warn("Preset saved but failed to reload list:", presetsResult.error);
        }
      } else {
        setToast({
          message: result.error || "Failed to save preset. Please try again.",
          type: "error",
        });
      }
    } catch (error) {
      console.error("Unexpected error saving preset:", error);
      setToast({
        message: error instanceof Error 
          ? `An unexpected error occurred: ${error.message}` 
          : "Failed to save preset. Please try again.",
        type: "error",
      });
    } finally {
      setIsSavingPreset(false);
      setTimeout(() => setToast(null), 5000);
    }
  }

  function handleLoadPreset(preset: any) {
    form.reset(preset.data);
    if (preset.data.headerConfig?.logo) {
      setLogoPreview(preset.data.headerConfig.logo);
    } else {
      setLogoPreview(null);
    }
    setToast({
      message: `Preset "${preset.name}" loaded successfully!`,
      type: "success",
    });
    setTimeout(() => setToast(null), 3000);
  }

  async function handleDeletePreset(presetId: string, presetName: string) {
    if (confirm(`Are you sure you want to delete preset "${presetName}"?`)) {
      try {
        const result = await deleteReportPreset(presetId);
        if (result.success) {
          setToast({
            message: result.message || "Preset deleted successfully!",
            type: "success",
          });
          const presetsResult = await getReportPresets();
          if (presetsResult.success && presetsResult.data) {
            setPresets(presetsResult.data);
          } else if (!presetsResult.success && presetsResult.error) {
            console.warn("Preset deleted but failed to reload list:", presetsResult.error);
          }
        } else {
          setToast({
            message: result.error || "Failed to delete preset. Please try again.",
            type: "error",
          });
        }
      } catch (error) {
        console.error("Unexpected error deleting preset:", error);
        setToast({
          message: error instanceof Error 
            ? `An unexpected error occurred: ${error.message}` 
            : "Failed to delete preset. Please try again.",
          type: "error",
        });
      } finally {
        setTimeout(() => setToast(null), 5000);
      }
    }
  }

  function handleResetToDefaults() {
    const defaultValues: ReportDesignFormValues = {
      headerConfig: {
        showHeader: true,
        showLogo: true,
        logo: null,
        logoPosition: "left",
        logoSize: "medium",
        showBusinessName: true,
        showAddress: true,
        showContactInfo: true,
        showTaxInfo: false,
        businessName: "LPG Nexus Distribution",
        address: "123 Business Street, City, State 12345",
        phoneNumber: "+91 9876543210",
        email: "info@lpgnexus.com",
        ntnGst: "",
        fontSize: 14,
        fontWeight: "regular",
        textColor: "#000000",
        lineHeight: 1.5,
        textAlignment: "left",
        headerLayout: "horizontal",
        showDivider: true,
        dividerStyle: "solid",
        dividerColor: "#e2e8f0",
        dividerThickness: 1,
        topMargin: 0,
        bottomMargin: 20,
      },
      footerConfig: {
        showFooter: true,
        footerLeftText: "Generated by LPG Nexus",
        footerCenterText: "",
        footerRightText: "",
        showPageNumber: true,
        showPrintedDate: true,
        showSignatureLine: false,
        fontSize: 12,
        textColor: "#666666",
        alignment: "center",
        signatureLabel: "Authorized Signature",
        showSignature: false,
        signatureAlignment: "center",
        signatureLineSpacing: 8,
        topMargin: 20,
        bottomMargin: 0,
      },
    };

    form.reset(defaultValues);
    setLogoPreview(null);
    setLogoFile(null);
    
    setToast({
      message: "Settings reset to default values",
      type: "success",
    });
    
    setTimeout(() => {
      setToast(null);
    }, 3000);
  }

  const headerConfig = form.watch("headerConfig");
  const footerConfig = form.watch("footerConfig");

  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <div className="text-slate-500">Loading report design...</div>
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-6">
      {/* Toast Notification */}
      {toast && (
        <div
          className={cn(
            "fixed right-6 top-20 z-50 flex items-center gap-3 rounded-xl border px-4 py-3 shadow-lg transition-all",
            toast.type === "success"
              ? "border-green-200 bg-green-50 text-green-800"
              : "border-red-200 bg-red-50 text-red-800",
          )}
        >
          {toast.type === "success" ? (
            <Check className="h-5 w-5" />
          ) : (
            <X className="h-5 w-5" />
          )}
          <span className="text-sm font-medium">{toast.message}</span>
          <button
            onClick={() => setToast(null)}
            className="ml-auto text-current opacity-70 hover:opacity-100"
          >
            <X className="h-4 w-4" />
          </button>
        </div>
      )}

      {/* Page Title */}
      <div className="rounded-[32px] border border-[#e5eaf4] bg-white p-6 shadow-none lg:p-8">
        <div>
          <h2 className="text-2xl font-bold text-slate-900">Report Design Settings</h2>
          <p className="mt-1 text-sm text-slate-500">Customize Report Header & Footer</p>
        </div>
      </div>

      <div className="grid gap-6 lg:grid-cols-2">
        {/* LEFT SIDE - Design Controls */}
        <div className="space-y-6">
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
            <Tabs defaultValue="header" className="w-full">
              <TabsList className="grid w-full grid-cols-3 rounded-xl bg-slate-100 p-1">
                <TabsTrigger 
                  value="header"
                  className="rounded-lg data-[state=active]:bg-white data-[state=active]:text-slate-900"
                >
                  Header Design
                </TabsTrigger>
                <TabsTrigger 
                  value="footer"
                  className="rounded-lg data-[state=active]:bg-white data-[state=active]:text-slate-900"
                >
                  Footer Design
                </TabsTrigger>
                <TabsTrigger 
                  value="preset"
                  className="rounded-lg data-[state=active]:bg-white data-[state=active]:text-slate-900"
                >
                  Save Preset
                </TabsTrigger>
              </TabsList>

              {/* HEADER DESIGN TAB */}
              <TabsContent value="header" className="space-y-6 mt-6">
                {/* Show/Hide Header Toggle */}
                <div className="rounded-[32px] border border-[#e5eaf4] bg-white p-6 shadow-none">
                  <div className="flex items-center justify-between">
                    <Label htmlFor="showHeader" className="text-base font-semibold text-slate-900 cursor-pointer">
                      Show Header
                    </Label>
                    <Switch
                      id="showHeader"
                      checked={headerConfig.showHeader ?? true}
                      onCheckedChange={(checked) => form.setValue("headerConfig.showHeader", checked)}
                    />
                  </div>
                  <p className="mt-2 text-sm text-slate-500">
                    Toggle to show or hide the header section in reports
                  </p>
                </div>

                {/* Logo Settings */}
                {headerConfig.showHeader !== false && (
                  <>
                    <div className="rounded-[32px] border border-[#e5eaf4] bg-white p-6 shadow-none">
                  <div className="mb-4">
                    <h3 className="text-lg font-semibold text-slate-900 flex items-center gap-2">
                      <ImageIcon className="h-5 w-5 text-[#2544d6]" />
                      Logo Settings
                    </h3>
                  </div>

                  <div className="space-y-4">
                    <div className="flex items-center justify-between">
                      <Label htmlFor="showLogo" className="text-sm font-medium text-slate-700 cursor-pointer">
                        Show Logo
                      </Label>
                      <Switch
                        id="showLogo"
                        checked={headerConfig.showLogo}
                        onCheckedChange={(checked) => form.setValue("headerConfig.showLogo", checked)}
                      />
                    </div>

                    {headerConfig.showLogo && (
                      <>
                        <div className="space-y-2">
                          <Label className="text-sm font-medium text-slate-700">Upload Logo (PNG / JPG)</Label>
                          <div className="flex items-center gap-4">
                            <input
                              ref={logoInputRef}
                              type="file"
                              accept="image/png,image/jpeg,image/jpg"
                              onChange={handleLogoUpload}
                              className="hidden"
                            />
                            <Button
                              type="button"
                              variant="outline"
                              onClick={() => logoInputRef.current?.click()}
                              className="rounded-xl border-slate-300"
                            >
                              <Upload className="mr-2 h-4 w-4" />
                              Upload Logo
                            </Button>
                            {logoPreview && (
                              <div className="relative h-16 w-16 overflow-hidden rounded-lg border border-slate-200">
                                <img src={logoPreview} alt="Logo preview" className="h-full w-full object-contain" />
                              </div>
                            )}
                          </div>
                        </div>

                        <div className="space-y-2">
                          <Label className="text-sm font-medium text-slate-700">Logo Position</Label>
                          <div className="flex gap-2">
                            <Button
                              type="button"
                              variant={headerConfig.logoPosition === "left" ? "default" : "outline"}
                              onClick={() => form.setValue("headerConfig.logoPosition", "left")}
                              className="rounded-xl"
                            >
                              Left
                            </Button>
                            <Button
                              type="button"
                              variant={headerConfig.logoPosition === "center" ? "default" : "outline"}
                              onClick={() => form.setValue("headerConfig.logoPosition", "center")}
                              className="rounded-xl"
                            >
                              Center
                            </Button>
                            <Button
                              type="button"
                              variant={headerConfig.logoPosition === "right" ? "default" : "outline"}
                              onClick={() => form.setValue("headerConfig.logoPosition", "right")}
                              className="rounded-xl"
                            >
                              Right
                            </Button>
                          </div>
                        </div>

                        <div className="space-y-2">
                          <Label className="text-sm font-medium text-slate-700">Logo Size</Label>
                          <Select
                            value={headerConfig.logoSize}
                            onValueChange={(value) => form.setValue("headerConfig.logoSize", value as "small" | "medium" | "large")}
                          >
                            <SelectTrigger className="rounded-xl border-slate-300">
                              <SelectValue />
                            </SelectTrigger>
                            <SelectContent>
                              <SelectItem value="small">Small</SelectItem>
                              <SelectItem value="medium">Medium</SelectItem>
                              <SelectItem value="large">Large</SelectItem>
                            </SelectContent>
                          </Select>
                        </div>
                      </>
                    )}
                  </div>
                    </div>

                    {/* Business Information */}
                    <div className="rounded-[32px] border border-[#e5eaf4] bg-white p-6 shadow-none">
                      <div className="mb-4">
                    <h3 className="text-lg font-semibold text-slate-900 flex items-center gap-2">
                      <Building2 className="h-5 w-5 text-[#2544d6]" />
                      Business Information
                    </h3>
                  </div>

                  <div className="space-y-4">
                    <div className="flex items-center justify-between">
                      <Label htmlFor="showBusinessName" className="text-sm font-medium text-slate-700 cursor-pointer">
                        Show Business Name
                      </Label>
                      <Switch
                        id="showBusinessName"
                        checked={headerConfig.showBusinessName}
                        onCheckedChange={(checked) => form.setValue("headerConfig.showBusinessName", checked)}
                      />
                    </div>

                    {headerConfig.showBusinessName && (
                      <div className="space-y-2">
                        <Label htmlFor="businessName" className="text-sm font-medium text-slate-700">Business Name</Label>
                        <Input
                          id="businessName"
                          {...form.register("headerConfig.businessName")}
                          className="rounded-xl border-slate-300"
                        />
                      </div>
                    )}

                    <div className="flex items-center justify-between">
                      <Label htmlFor="showAddress" className="text-sm font-medium text-slate-700 cursor-pointer">
                        Show Address
                      </Label>
                      <Switch
                        id="showAddress"
                        checked={headerConfig.showAddress}
                        onCheckedChange={(checked) => form.setValue("headerConfig.showAddress", checked)}
                      />
                    </div>

                    {headerConfig.showAddress && (
                      <div className="space-y-2">
                        <Label htmlFor="address" className="text-sm font-medium text-slate-700">Address</Label>
                        <Textarea
                          id="address"
                          {...form.register("headerConfig.address")}
                          rows={2}
                          className="rounded-xl border-slate-300"
                        />
                      </div>
                    )}

                    <div className="flex items-center justify-between">
                      <Label htmlFor="showContactInfo" className="text-sm font-medium text-slate-700 cursor-pointer">
                        Show Contact Info
                      </Label>
                      <Switch
                        id="showContactInfo"
                        checked={headerConfig.showContactInfo}
                        onCheckedChange={(checked) => form.setValue("headerConfig.showContactInfo", checked)}
                      />
                    </div>

                    {headerConfig.showContactInfo && (
                      <div className="grid gap-4 md:grid-cols-2">
                        <div className="space-y-2">
                          <Label htmlFor="phoneNumber" className="text-sm font-medium text-slate-700">Phone Number</Label>
                          <Input
                            id="phoneNumber"
                            {...form.register("headerConfig.phoneNumber")}
                            className="rounded-xl border-slate-300"
                          />
                        </div>
                        <div className="space-y-2">
                          <Label htmlFor="email" className="text-sm font-medium text-slate-700">Email</Label>
                          <Input
                            id="email"
                            {...form.register("headerConfig.email")}
                            type="email"
                            className="rounded-xl border-slate-300"
                          />
                        </div>
                      </div>
                    )}

                    <div className="flex items-center justify-between">
                      <Label htmlFor="showTaxInfo" className="text-sm font-medium text-slate-700 cursor-pointer">
                        Show Tax Info (NTN/GST)
                      </Label>
                      <Switch
                        id="showTaxInfo"
                        checked={headerConfig.showTaxInfo}
                        onCheckedChange={(checked) => form.setValue("headerConfig.showTaxInfo", checked)}
                      />
                    </div>

                    {headerConfig.showTaxInfo && (
                      <div className="space-y-2">
                        <Label htmlFor="ntnGst" className="text-sm font-medium text-slate-700">NTN / GST (Optional)</Label>
                        <Input
                          id="ntnGst"
                          {...form.register("headerConfig.ntnGst")}
                          className="rounded-xl border-slate-300"
                        />
                      </div>
                    )}
                  </div>
                </div>

                {/* Header Text Styling */}
                <div className="rounded-[32px] border border-[#e5eaf4] bg-white p-6 shadow-none">
                  <div className="mb-4">
                    <h3 className="text-lg font-semibold text-slate-900 flex items-center gap-2">
                      <Type className="h-5 w-5 text-[#2544d6]" />
                      Text Styling
                    </h3>
                  </div>

                  <div className="space-y-4">
                    <div className="space-y-2">
                      <Label className="text-sm font-medium text-slate-700">Font Size: {headerConfig.fontSize}px</Label>
                      <input
                        type="range"
                        min={8}
                        max={24}
                        step={1}
                        value={headerConfig.fontSize}
                        onChange={(e) => form.setValue("headerConfig.fontSize", parseInt(e.target.value))}
                        className="w-full h-2 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-[#1c5bff]"
                      />
                    </div>

                    <div className="space-y-2">
                      <Label className="text-sm font-medium text-slate-700">Font Weight</Label>
                      <Select
                        value={headerConfig.fontWeight}
                        onValueChange={(value) => form.setValue("headerConfig.fontWeight", value as "regular" | "medium" | "bold")}
                      >
                        <SelectTrigger className="rounded-xl border-slate-300">
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="regular">Regular</SelectItem>
                          <SelectItem value="medium">Medium</SelectItem>
                          <SelectItem value="bold">Bold</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>

                    <div className="space-y-2">
                      <Label className="text-sm font-medium text-slate-700 flex items-center gap-2">
                        <Palette className="h-4 w-4" />
                        Text Color
                      </Label>
                      <div className="flex gap-2">
                        <Input
                          type="color"
                          value={headerConfig.textColor}
                          onChange={(e) => form.setValue("headerConfig.textColor", e.target.value)}
                          className="h-10 w-20 rounded-xl border-slate-300 cursor-pointer"
                        />
                        <Input
                          value={headerConfig.textColor}
                          onChange={(e) => form.setValue("headerConfig.textColor", e.target.value)}
                          className="rounded-xl border-slate-300"
                        />
                      </div>
                    </div>

                    <div className="space-y-2">
                      <Label className="text-sm font-medium text-slate-700">Line Height: {headerConfig.lineHeight}</Label>
                      <input
                        type="range"
                        min={1}
                        max={2}
                        step={0.1}
                        value={headerConfig.lineHeight}
                        onChange={(e) => form.setValue("headerConfig.lineHeight", parseFloat(e.target.value))}
                        className="w-full h-2 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-[#1c5bff]"
                      />
                    </div>
                      </div>
                    </div>

                    {/* Alignment & Layout */}
                    <div className="rounded-[32px] border border-[#e5eaf4] bg-white p-6 shadow-none">
                      <div className="mb-4">
                    <h3 className="text-lg font-semibold text-slate-900 flex items-center gap-2">
                      <AlignLeft className="h-5 w-5 text-[#2544d6]" />
                      Alignment & Layout
                    </h3>
                  </div>

                  <div className="space-y-4">
                    <div className="space-y-2">
                      <Label className="text-sm font-medium text-slate-700">Text Alignment</Label>
                      <div className="flex gap-4">
                        <Button
                          type="button"
                          variant={headerConfig.textAlignment === "left" ? "default" : "outline"}
                          onClick={() => form.setValue("headerConfig.textAlignment", "left")}
                          className="rounded-xl"
                        >
                          <AlignLeft className="h-4 w-4" />
                        </Button>
                        <Button
                          type="button"
                          variant={headerConfig.textAlignment === "center" ? "default" : "outline"}
                          onClick={() => form.setValue("headerConfig.textAlignment", "center")}
                          className="rounded-xl"
                        >
                          <AlignCenter className="h-4 w-4" />
                        </Button>
                        <Button
                          type="button"
                          variant={headerConfig.textAlignment === "right" ? "default" : "outline"}
                          onClick={() => form.setValue("headerConfig.textAlignment", "right")}
                          className="rounded-xl"
                        >
                          <AlignRight className="h-4 w-4" />
                        </Button>
                      </div>
                    </div>

                    <div className="space-y-2">
                      <Label className="text-sm font-medium text-slate-700">Header Layout</Label>
                      <div className="flex gap-2">
                        <Button
                          type="button"
                          variant={headerConfig.headerLayout === "horizontal" ? "default" : "outline"}
                          onClick={() => form.setValue("headerConfig.headerLayout", "horizontal")}
                          className="rounded-xl"
                        >
                          Logo + Text (Horizontal)
                        </Button>
                        <Button
                          type="button"
                          variant={headerConfig.headerLayout === "vertical" ? "default" : "outline"}
                          onClick={() => form.setValue("headerConfig.headerLayout", "vertical")}
                          className="rounded-xl"
                        >
                          Logo Top, Text Below (Vertical)
                        </Button>
                      </div>
                    </div>
                      </div>
                    </div>

                    {/* Header Divider */}
                    <div className="rounded-[32px] border border-[#e5eaf4] bg-white p-6 shadow-none">
                      <div className="mb-4">
                    <h3 className="text-lg font-semibold text-slate-900 flex items-center gap-2">
                      <Minus className="h-5 w-5 text-[#2544d6]" />
                      Header Divider
                    </h3>
                  </div>

                  <div className="space-y-4">
                    <div className="flex items-center justify-between">
                      <Label htmlFor="showDivider" className="text-sm font-medium text-slate-700 cursor-pointer">
                        Show Divider Line
                      </Label>
                      <Switch
                        id="showDivider"
                        checked={headerConfig.showDivider}
                        onCheckedChange={(checked) => form.setValue("headerConfig.showDivider", checked)}
                      />
                    </div>

                    {headerConfig.showDivider && (
                      <>
                        <div className="space-y-2">
                          <Label className="text-sm font-medium text-slate-700">Divider Style</Label>
                          <Select
                            value={headerConfig.dividerStyle}
                            onValueChange={(value) => form.setValue("headerConfig.dividerStyle", value as "solid" | "dotted" | "dashed")}
                          >
                            <SelectTrigger className="rounded-xl border-slate-300">
                              <SelectValue />
                            </SelectTrigger>
                            <SelectContent>
                              <SelectItem value="solid">Solid</SelectItem>
                              <SelectItem value="dotted">Dotted</SelectItem>
                              <SelectItem value="dashed">Dashed</SelectItem>
                            </SelectContent>
                          </Select>
                        </div>

                        <div className="space-y-2">
                          <Label className="text-sm font-medium text-slate-700 flex items-center gap-2">
                            <Palette className="h-4 w-4" />
                            Divider Color
                          </Label>
                          <div className="flex gap-2">
                            <Input
                              type="color"
                              value={headerConfig.dividerColor}
                              onChange={(e) => form.setValue("headerConfig.dividerColor", e.target.value)}
                              className="h-10 w-20 rounded-xl border-slate-300 cursor-pointer"
                            />
                            <Input
                              value={headerConfig.dividerColor}
                              onChange={(e) => form.setValue("headerConfig.dividerColor", e.target.value)}
                              className="rounded-xl border-slate-300"
                            />
                          </div>
                        </div>

                        <div className="space-y-2">
                          <Label className="text-sm font-medium text-slate-700">Divider Thickness: {headerConfig.dividerThickness}px</Label>
                          <input
                            type="range"
                            min={1}
                            max={5}
                            step={1}
                            value={headerConfig.dividerThickness}
                            onChange={(e) => form.setValue("headerConfig.dividerThickness", parseInt(e.target.value))}
                            className="w-full h-2 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-[#1c5bff]"
                          />
                        </div>
                      </>
                    )}
                      </div>
                    </div>

                    {/* Header Margins */}
                    <div className="rounded-[32px] border border-[#e5eaf4] bg-white p-6 shadow-none">
                      <div className="mb-4">
                        <h3 className="text-lg font-semibold text-slate-900 flex items-center gap-2">
                          <Minus className="h-5 w-5 text-[#2544d6]" />
                          Header Spacing
                        </h3>
                      </div>

                      <div className="space-y-4">
                        <div className="space-y-2">
                          <Label className="text-sm font-medium text-slate-700">Top Margin: {headerConfig.topMargin ?? 0}px</Label>
                          <input
                            type="range"
                            min={0}
                            max={100}
                            step={1}
                            value={headerConfig.topMargin ?? 0}
                            onChange={(e) => form.setValue("headerConfig.topMargin", parseInt(e.target.value))}
                            className="w-full h-2 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-[#1c5bff]"
                          />
                          <p className="text-xs text-slate-500">Space above the header</p>
                        </div>

                        <div className="space-y-2">
                          <div className="flex items-center justify-between">
                            <Label className="text-sm font-medium text-slate-700">Bottom Margin: {headerConfig.bottomMargin ?? 20}px</Label>
                            <Button
                              type="button"
                              variant="outline"
                              size="sm"
                              onClick={() => form.setValue("headerConfig.bottomMargin", 0)}
                              className="h-7 px-2 text-xs rounded-lg"
                            >
                              Reset
                            </Button>
                          </div>
                          <input
                            type="range"
                            min={-50}
                            max={100}
                            step={1}
                            value={headerConfig.bottomMargin ?? 20}
                            onChange={(e) => form.setValue("headerConfig.bottomMargin", parseInt(e.target.value))}
                            className="w-full h-2 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-[#1c5bff]"
                          />
                          <p className="text-xs text-slate-500">Space between header and body (can be negative to reduce space)</p>
                        </div>
                      </div>
                    </div>
                  </>
                )}
              </TabsContent>

              {/* FOOTER DESIGN TAB */}
              <TabsContent value="footer" className="space-y-6 mt-6">
                {/* Show/Hide Footer Toggle */}
                <div className="rounded-[32px] border border-[#e5eaf4] bg-white p-6 shadow-none">
                  <div className="flex items-center justify-between">
                    <Label htmlFor="showFooter" className="text-base font-semibold text-slate-900 cursor-pointer">
                      Show Footer
                    </Label>
                    <Switch
                      id="showFooter"
                      checked={footerConfig.showFooter ?? true}
                      onCheckedChange={(checked) => form.setValue("footerConfig.showFooter", checked)}
                    />
                  </div>
                  <p className="mt-2 text-sm text-slate-500">
                    Toggle to show or hide the footer section in reports
                  </p>
                </div>

                {/* Footer Content */}
                {footerConfig.showFooter !== false && (
                  <>
                    <div className="rounded-[32px] border border-[#e5eaf4] bg-white p-6 shadow-none">
                  <div className="mb-4">
                    <h3 className="text-lg font-semibold text-slate-900 flex items-center gap-2">
                      <FileText className="h-5 w-5 text-[#2544d6]" />
                      Footer Content
                    </h3>
                  </div>

                  <div className="space-y-4">
                    <div className="space-y-2">
                      <Label htmlFor="footerLeftText" className="text-sm font-medium text-slate-700">Footer Left Text</Label>
                      <Input
                        id="footerLeftText"
                        {...form.register("footerConfig.footerLeftText")}
                        placeholder='e.g. "Generated by LPG Nexus"'
                        className="rounded-xl border-slate-300"
                      />
                    </div>

                    <div className="space-y-2">
                      <Label htmlFor="footerCenterText" className="text-sm font-medium text-slate-700">Footer Center Text (Optional)</Label>
                      <Input
                        id="footerCenterText"
                        {...form.register("footerConfig.footerCenterText")}
                        className="rounded-xl border-slate-300"
                      />
                    </div>

                    <div className="space-y-2">
                      <Label htmlFor="footerRightText" className="text-sm font-medium text-slate-700">Footer Right Text (Page Number / Date)</Label>
                      <Input
                        id="footerRightText"
                        {...form.register("footerConfig.footerRightText")}
                        className="rounded-xl border-slate-300"
                      />
                    </div>

                    <div className="flex items-center justify-between">
                      <Label htmlFor="showPageNumber" className="text-sm font-medium text-slate-700 cursor-pointer">
                        Show Page Number
                      </Label>
                      <Switch
                        id="showPageNumber"
                        checked={footerConfig.showPageNumber}
                        onCheckedChange={(checked) => form.setValue("footerConfig.showPageNumber", checked)}
                      />
                    </div>

                    <div className="flex items-center justify-between">
                      <Label htmlFor="showPrintedDate" className="text-sm font-medium text-slate-700 cursor-pointer">
                        Show Printed Date
                      </Label>
                      <Switch
                        id="showPrintedDate"
                        checked={footerConfig.showPrintedDate}
                        onCheckedChange={(checked) => form.setValue("footerConfig.showPrintedDate", checked)}
                      />
                    </div>

                    <div className="flex items-center justify-between">
                      <Label htmlFor="showSignatureLine" className="text-sm font-medium text-slate-700 cursor-pointer">
                        Show Signature Line
                      </Label>
                      <Switch
                        id="showSignatureLine"
                        checked={footerConfig.showSignatureLine || false}
                        onCheckedChange={(checked) => {
                          form.setValue("footerConfig.showSignatureLine", checked, { shouldDirty: true, shouldValidate: true });
                        }}
                      />
                    </div>
                  </div>
                </div>

                {/* Footer Styling */}
                <div className="rounded-[32px] border border-[#e5eaf4] bg-white p-6 shadow-none">
                  <div className="mb-4">
                    <h3 className="text-lg font-semibold text-slate-900 flex items-center gap-2">
                      <Palette className="h-5 w-5 text-[#2544d6]" />
                      Footer Styling
                    </h3>
                  </div>

                  <div className="space-y-4">
                    <div className="space-y-2">
                      <Label className="text-sm font-medium text-slate-700">Font Size: {form.watch("footerConfig.fontSize")}px</Label>
                      <input
                        type="range"
                        min={8}
                        max={24}
                        step={1}
                        value={form.watch("footerConfig.fontSize")}
                        onChange={(e) => {
                          const value = parseInt(e.target.value);
                          form.setValue("footerConfig.fontSize", value, { shouldDirty: true, shouldValidate: true });
                        }}
                        className="w-full h-2 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-[#1c5bff]"
                      />
                    </div>

                    <div className="space-y-2">
                      <Label className="text-sm font-medium text-slate-700 flex items-center gap-2">
                        <Palette className="h-4 w-4" />
                        Text Color
                      </Label>
                      <div className="flex gap-2">
                        <Input
                          type="color"
                          value={footerConfig.textColor}
                          onChange={(e) => form.setValue("footerConfig.textColor", e.target.value)}
                          className="h-10 w-20 rounded-xl border-slate-300 cursor-pointer"
                        />
                        <Input
                          value={footerConfig.textColor}
                          onChange={(e) => form.setValue("footerConfig.textColor", e.target.value)}
                          className="rounded-xl border-slate-300"
                        />
                      </div>
                    </div>

                    <div className="space-y-2">
                      <Label className="text-sm font-medium text-slate-700">Alignment</Label>
                      <div className="flex gap-4">
                        <Button
                          type="button"
                          variant={footerConfig.alignment === "left" ? "default" : "outline"}
                          onClick={() => form.setValue("footerConfig.alignment", "left")}
                          className="rounded-xl"
                        >
                          <AlignLeft className="h-4 w-4" />
                        </Button>
                        <Button
                          type="button"
                          variant={footerConfig.alignment === "center" ? "default" : "outline"}
                          onClick={() => form.setValue("footerConfig.alignment", "center")}
                          className="rounded-xl"
                        >
                          <AlignCenter className="h-4 w-4" />
                        </Button>
                        <Button
                          type="button"
                          variant={footerConfig.alignment === "right" ? "default" : "outline"}
                          onClick={() => form.setValue("footerConfig.alignment", "right")}
                          className="rounded-xl"
                        >
                          <AlignRight className="h-4 w-4" />
                        </Button>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Signature */}
                <div className="rounded-[32px] border border-[#e5eaf4] bg-white p-6 shadow-none">
                  <div className="mb-4">
                    <h3 className="text-lg font-semibold text-slate-900 flex items-center gap-2">
                      <FileSignature className="h-5 w-5 text-[#2544d6]" />
                      Signature (Optional)
                    </h3>
                  </div>

                  <div className="space-y-4">
                    <div className="space-y-2">
                      <Label htmlFor="signatureLabel" className="text-sm font-medium text-slate-700">Signature Label</Label>
                      <Input
                        id="signatureLabel"
                        {...form.register("footerConfig.signatureLabel")}
                        placeholder='e.g. "Authorized Signature"'
                        className="rounded-xl border-slate-300"
                      />
                    </div>

                    <div className="space-y-2">
                      <Label className="text-sm font-medium text-slate-700">Signature Alignment</Label>
                      <div className="flex gap-2">
                        <Button
                          type="button"
                          variant={footerConfig.signatureAlignment === "left" ? "default" : "outline"}
                          onClick={() => form.setValue("footerConfig.signatureAlignment", "left")}
                          className="rounded-xl"
                        >
                          <AlignLeft className="h-4 w-4" />
                        </Button>
                        <Button
                          type="button"
                          variant={footerConfig.signatureAlignment === "center" ? "default" : "outline"}
                          onClick={() => form.setValue("footerConfig.signatureAlignment", "center")}
                          className="rounded-xl"
                        >
                          <AlignCenter className="h-4 w-4" />
                        </Button>
                        <Button
                          type="button"
                          variant={footerConfig.signatureAlignment === "right" ? "default" : "outline"}
                          onClick={() => form.setValue("footerConfig.signatureAlignment", "right")}
                          className="rounded-xl"
                        >
                          <AlignRight className="h-4 w-4" />
                        </Button>
                      </div>
                    </div>

                    <div className="space-y-2">
                      <Label className="text-sm font-medium text-slate-700">Line Spacing: {form.watch("footerConfig.signatureLineSpacing")}px</Label>
                      <input
                        type="range"
                        min={0}
                        max={30}
                        step={1}
                        value={form.watch("footerConfig.signatureLineSpacing")}
                        onChange={(e) => {
                          const value = parseInt(e.target.value);
                          form.setValue("footerConfig.signatureLineSpacing", value, { shouldDirty: true, shouldValidate: true });
                        }}
                        className="w-full h-2 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-[#1c5bff]"
                      />
                    </div>
                  </div>
                </div>

                    {/* Footer Margins */}
                    <div className="rounded-[32px] border border-[#e5eaf4] bg-white p-6 shadow-none">
                      <div className="mb-4">
                        <h3 className="text-lg font-semibold text-slate-900 flex items-center gap-2">
                          <Minus className="h-5 w-5 text-[#2544d6]" />
                          Footer Spacing
                        </h3>
                      </div>

                      <div className="space-y-4">
                        <div className="space-y-2">
                          <div className="flex items-center justify-between">
                            <Label className="text-sm font-medium text-slate-700">Top Margin: {footerConfig.topMargin ?? 20}px</Label>
                            <Button
                              type="button"
                              variant="outline"
                              size="sm"
                              onClick={() => form.setValue("footerConfig.topMargin", 0)}
                              className="h-7 px-2 text-xs rounded-lg"
                            >
                              Reset
                            </Button>
                          </div>
                          <input
                            type="range"
                            min={-50}
                            max={100}
                            step={1}
                            value={footerConfig.topMargin ?? 20}
                            onChange={(e) => form.setValue("footerConfig.topMargin", parseInt(e.target.value))}
                            className="w-full h-2 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-[#1c5bff]"
                          />
                          <p className="text-xs text-slate-500">Space between body and footer (can be negative to reduce space)</p>
                        </div>

                        <div className="space-y-2">
                          <Label className="text-sm font-medium text-slate-700">Bottom Margin: {footerConfig.bottomMargin ?? 0}px</Label>
                          <input
                            type="range"
                            min={0}
                            max={100}
                            step={1}
                            value={footerConfig.bottomMargin ?? 0}
                            onChange={(e) => form.setValue("footerConfig.bottomMargin", parseInt(e.target.value))}
                            className="w-full h-2 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-[#1c5bff]"
                          />
                          <p className="text-xs text-slate-500">Space below the footer</p>
                        </div>
                      </div>
                    </div>
                  </>
                )}
              </TabsContent>

              {/* SAVE PRESET TAB */}
              <TabsContent value="preset" className="space-y-6 mt-6">
                {/* Save New Preset */}
                <div className="rounded-[32px] border border-[#e5eaf4] bg-white p-6 shadow-none">
                  <div className="mb-4">
                    <h3 className="text-lg font-semibold text-slate-900 flex items-center gap-2">
                      <Bookmark className="h-5 w-5 text-[#2544d6]" />
                      Save Preset
                    </h3>
                  </div>

                  <div className="space-y-4">
                    <div className="space-y-2">
                      <Label htmlFor="presetName" className="text-sm font-medium text-slate-700">
                        Preset Name
                      </Label>
                      <div className="flex gap-2">
                        <Input
                          id="presetName"
                          value={presetName}
                          onChange={(e) => setPresetName(e.target.value)}
                          placeholder="Enter preset name (e.g., 'My Custom Design')"
                          className="rounded-xl border-slate-300"
                          onKeyDown={(e) => {
                            if (e.key === "Enter" && presetName.trim()) {
                              e.preventDefault();
                              handleSavePreset();
                            }
                          }}
                        />
                        <Button
                          type="button"
                          onClick={handleSavePreset}
                          disabled={isSavingPreset || !presetName.trim()}
                          className="rounded-xl bg-[#1c5bff] text-white hover:bg-[#1647c4]"
                        >
                          {isSavingPreset ? "Saving..." : "Save Preset"}
                        </Button>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Saved Presets */}
                <div className="rounded-[32px] border border-[#e5eaf4] bg-white p-6 shadow-none">
                  <div className="mb-4">
                    <h3 className="text-lg font-semibold text-slate-900 flex items-center gap-2">
                      <Bookmark className="h-5 w-5 text-[#2544d6]" />
                      Saved Presets
                    </h3>
                    <p className="mt-1 text-sm text-slate-500">
                      Click on a preset to load it. Delete manually to remove.
                    </p>
                  </div>

                  <div className="space-y-2">
                    {presets.saved.length === 0 ? (
                      <p className="text-sm text-slate-500 py-4 text-center">
                        No saved presets yet. Save your first preset above.
                      </p>
                    ) : (
                      presets.saved.map((preset: any) => (
                        <div
                          key={preset.id}
                          className="flex items-center justify-between rounded-lg border border-slate-200 bg-slate-50 p-3 hover:bg-slate-100 transition-colors"
                        >
                          <button
                            type="button"
                            onClick={() => handleLoadPreset(preset)}
                            className="flex-1 text-left"
                          >
                            <div className="font-medium text-slate-900">{preset.name}</div>
                            <div className="text-xs text-slate-500">
                              {new Date(preset.createdAt).toLocaleDateString()}
                            </div>
                          </button>
                          <Button
                            type="button"
                            variant="ghost"
                            size="sm"
                            onClick={() => handleDeletePreset(preset.id, preset.name)}
                            className="h-8 w-8 text-red-600 hover:text-red-700 hover:bg-red-50"
                          >
                            <Trash2 className="h-4 w-4" />
                          </Button>
                        </div>
                      ))
                    )}
                  </div>
                </div>

                {/* History (Last 5 Changes) */}
                <div className="rounded-[32px] border border-[#e5eaf4] bg-white p-6 shadow-none">
                  <div className="mb-4">
                    <h3 className="text-lg font-semibold text-slate-900 flex items-center gap-2">
                      <Clock className="h-5 w-5 text-[#2544d6]" />
                      Recent History (Last 5 Changes)
                    </h3>
                    <p className="mt-1 text-sm text-slate-500">
                      Automatically saved when you save a preset. Oldest is removed when 6th is added.
                    </p>
                  </div>

                  <div className="space-y-2">
                    {presets.history.length === 0 ? (
                      <p className="text-sm text-slate-500 py-4 text-center">
                        No history yet. Save a preset to see it here.
                      </p>
                    ) : (
                      presets.history.map((preset: any) => (
                        <button
                          key={preset.id}
                          type="button"
                          onClick={() => handleLoadPreset(preset)}
                          className="w-full text-left rounded-lg border border-slate-200 bg-slate-50 p-3 hover:bg-slate-100 transition-colors"
                        >
                          <div className="font-medium text-slate-900">{preset.name}</div>
                          <div className="text-xs text-slate-500">
                            {new Date(preset.createdAt).toLocaleString()}
                          </div>
                        </button>
                      ))
                    )}
                  </div>
                </div>
              </TabsContent>
            </Tabs>

            {/* Save Button */}
            <div className="flex items-center justify-between gap-4 border-t border-slate-200 pt-6">
              <Button
                type="button"
                variant="outline"
                onClick={handleResetToDefaults}
                className="gap-2 rounded-xl border-slate-300 px-6 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50"
              >
                <RotateCcw className="h-4 w-4" />
                Default Settings
              </Button>
              <Button
                type="submit"
                disabled={isSubmitting}
                className="gap-2 rounded-xl bg-[#1c5bff] px-6 py-2.5 text-sm font-semibold text-white hover:bg-[#1647c4] disabled:opacity-60"
              >
                <Save className="h-4 w-4" />
                {isSubmitting ? "Saving..." : "Save Changes"}
              </Button>
            </div>
          </form>
        </div>

        {/* RIGHT SIDE - Live Preview */}
        <div className="lg:sticky lg:top-6 lg:self-start">
          <div className="rounded-[32px] border border-[#e5eaf4] bg-white p-6 shadow-none">
            <div className="mb-4">
              <h3 className="text-lg font-semibold text-slate-900">Live Preview</h3>
              <p className="text-sm text-slate-500">Preview your report header and footer design</p>
            </div>
            <ReportPreview headerConfig={headerConfig} footerConfig={footerConfig} />
          </div>
        </div>
      </div>
    </div>
  );
}
